services:

  gateway:
    path: gateway
 
  auth:
    path: auth
    dependsOn:
      - gateway
 
  project:
    path: project
    dependsOn:
      - gateway

  test:
    path: test
    dependsOn:
      - gateway