service: abcauth
provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    restApiId:
      "Fn::ImportValue": SharedGWrestApiId
    restApiRootResourceId:
      "Fn::ImportValue": SharedGWrootResourceId
functions:
  auth:
    handler: index.handler
    name: abcauth
    events:
      # - httpApi:
      #     path: /auth/{proxy+}
      #     method: '*'
      - http:
          path: /users
          method: ANY
      - http:
          path: /users/{proxy+}
          method: ANY
      - http:
          path: /companies
          method: ANY
      - http:
          path: /companies/{proxy+}
          method: ANY