service: abcproject
provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    restApiId:
      "Fn::ImportValue": SharedGWrestApiId
    restApiRootResourceId:
      "Fn::ImportValue": SharedGWrootResourceId
functions:
  project:
    handler: index.handler
    name: abcproject
    events:
      - http:
          path: /projects/{proxy+}
          method: ANY
      - http:
          path: /projects
          method: ANY
plugins:
  - serverless-offline