service: abcproject
provider:
  name: aws
  runtime: nodejs18.x
  apiGateway:
    restApiId:
      "Fn::ImportValue": SharedGWrestApiId
    restApiRootResourceId:
      "Fn::ImportValue": SharedGWrootResourceId
functions:
  project:
    handler: app.handler
    name: abcproject
    events:
      - http:
          path: /project/{proxy+}
          method: ANY
      - http:
          path: /project
          method: ANY
# plugins:
#   - serverless-offline